name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Checkout Hadoop winutils
      if: runner.os == 'Windows'
      uses: actions/checkout@v2
      with:
        repository: cdarlint/winutils
        path: hadoop
    - name: Export Hadoop winutils
      if: runner.os == 'Windows'
      run: |
        echo "::set-env name=HADOOP_HOME::${{ github.workspace }}\hadoop\hadoop-3.1.2"
        echo "::set-env name=PATH::$env:Path;${{ github.workspace }}\hadoop\hadoop-3.1.2\bin"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Check with Gradle
      run: ./gradlew check --info
